/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/plugin/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AcademicCMSPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/plugin/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  codeFolderPath: "",
  externalCodeBasePath: ""
};
var AcademicCMSSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Academic CMS Settings" });
    new import_obsidian.Setting(containerEl).setName("Code folder path").setDesc("Vault-relative path for code/ when assignment type includes code (e.g. practico). Leave empty for default vault folder structure: course/assignDir/folder/code. Agnostic, no hardcode ~/Projects.").addText(
      (text) => text.setPlaceholder("e.g. 30-assignments or leave empty").setValue(this.plugin.settings.codeFolderPath).onChange(async (value) => {
        this.plugin.settings.codeFolderPath = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("hr");
    new import_obsidian.Setting(containerEl).setName("External code base path").setDesc("Absolute host filesystem path for code symlink. Plugin creates <externalBase>/<subject>/<folderName>/ linked from vault. Leave empty for default vault folder. Desktop only.").addText(
      (text) => text.setPlaceholder("e.g. /home/matt/Projects/.../isft151-analisis-sistemas").setValue(this.plugin.settings.externalCodeBasePath).onChange(async (value) => {
        this.plugin.settings.externalCodeBasePath = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/adapters/obsidian/modal_adapter.ts
var import_obsidian2 = require("obsidian");

// src/domain/assignment_types.ts
var canonicalTypes = {
  practico: "Trabajo Pr\xE1ctico",
  laboratorio: "Laboratorio",
  kata: "Kata",
  cuestionario: "Cuestionario",
  trivia: "Trivia",
  investigacion: "Investigaci\xF3n",
  caso: "Caso",
  ejercicios: "Ejercicios",
  parcial: "Examen Parcial",
  final: "Examen Final"
};
var aliasMap = {
  practica: "practico",
  "trabajo-practico": "practico"
};
var typeDisplayNames = {
  ...canonicalTypes,
  practica: canonicalTypes.practico,
  "trabajo-practico": canonicalTypes.practico
};
var typeOptions = { ...canonicalTypes };
var scaffoldTemplates = {
  practico: ["_assets", "deliverable"],
  practica: ["_assets", "deliverable"],
  "trabajo-practico": ["_assets", "deliverable"],
  laboratorio: ["_assets", "deliverable"],
  kata: ["_assets", "deliverable"],
  cuestionario: ["_assets", "deliverable"],
  trivia: ["_assets", "deliverable"],
  investigacion: ["_assets", "deliverable"],
  caso: ["_assets", "deliverable"],
  ejercicios: ["_assets", "deliverable"],
  parcial: ["_assets"],
  final: ["_assets"]
};
var codeTypes = ["practico", "laboratorio", "kata"];
var typeAliases = {
  practico: ["practico", "practica", "trabajo-practico"]
};
function resolveType(slug) {
  return aliasMap[slug] || slug;
}
function getDisplayName(slug) {
  const canonical = resolveType(slug);
  return canonicalTypes[canonical] || typeDisplayNames[slug] || slug;
}

// src/adapters/obsidian/modal_adapter.ts
var EXTENSION_MAP = {
  "word-document": ".docx",
  PDF: ".pdf",
  "source-code": ".cpp",
  presentation: ".pptx",
  video: ".mp4",
  handwritten: ""
};
var AssignmentFormModal = class extends import_obsidian2.Modal {
  constructor(app, prefill = {}) {
    super(app);
    this.done = false;
    this.data = {
      type: "practico",
      topic: "Introduccion",
      unit: "01",
      date: "",
      due_date: "",
      difficulty: "medium",
      priority: "medium",
      submission_type: "PDF",
      submission_platform: "Google_Classroom",
      submission_link: "",
      instructions_link: "",
      ai_chat_links: ""
    };
    if (prefill.unit)
      this.data.unit = prefill.unit;
    if (prefill.assignment_number)
      this.data.assignment_number = prefill.assignment_number;
    if (prefill.date)
      this.data.date = prefill.date;
    if (prefill.due_date)
      this.data.due_date = prefill.due_date;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Nueva Actividad" });
    new import_obsidian2.Setting(contentEl).setName("Tipo").addDropdown((d) => {
      for (const [value, label] of Object.entries(typeOptions)) {
        d.addOption(value, label);
      }
      d.setValue(this.data.type);
      d.onChange((v) => this.data.type = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Tema").addText((t) => {
      t.setValue(this.data.topic);
      t.onChange((v) => this.data.topic = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Unidad").addText((t) => {
      t.setValue(this.data.unit);
      t.onChange((v) => this.data.unit = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Fecha de asignaci\xF3n").addText((t) => {
      t.setValue(this.data.date);
      t.onChange((v) => this.data.date = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Fecha de entrega").addText((t) => {
      t.setValue(this.data.due_date);
      t.onChange((v) => this.data.due_date = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Dificultad").addDropdown((d) => {
      d.addOption("very-easy", "Muy Facil").addOption("easy", "Facil").addOption("medium", "Media").addOption("hard", "Dificil").addOption("very-hard", "Muy Dificil");
      d.setValue(this.data.difficulty);
      d.onChange((v) => this.data.difficulty = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Prioridad").addDropdown((d) => {
      d.addOption("low", "Baja").addOption("medium", "Media").addOption("high", "Alta").addOption("urgent", "Urgente");
      d.setValue(this.data.priority);
      d.onChange((v) => this.data.priority = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Formato").addDropdown((d) => {
      d.addOption("word-document", "Documento Word").addOption("PDF", "PDF").addOption("source-code", "Codigo Fuente").addOption("presentation", "Presentacion").addOption("video", "Video").addOption("handwritten", "Manuscrito");
      d.setValue(this.data.submission_type);
      d.onChange((v) => this.data.submission_type = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Plataforma").addDropdown((d) => {
      d.addOption("Google_Classroom", "Google Classroom").addOption("Moodle", "Moodle").addOption("Email", "Email").addOption("GitHub", "GitHub").addOption("in_person", "Entrega Fisica").addOption("no-submit", "Sin Entrega");
      d.setValue(this.data.submission_platform);
      d.onChange((v) => this.data.submission_platform = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Enlace de entrega").addText((t) => {
      t.setValue(this.data.submission_link);
      t.onChange((v) => this.data.submission_link = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Instrucciones").addText((t) => {
      t.setValue(this.data.instructions_link);
      t.onChange((v) => this.data.instructions_link = v);
    });
    new import_obsidian2.Setting(contentEl).setName("Chats IA").addTextArea((t) => {
      t.setPlaceholder("https://chat.deepseek.com/...\nhttps://notebooklm.google.com/...");
      t.setValue(this.data.ai_chat_links);
      t.onChange((v) => this.data.ai_chat_links = v);
    });
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Cancelar").onClick(() => this.finish(null))
    ).addButton(
      (btn) => btn.setButtonText("Crear Actividad").setCta().onClick(() => {
        const canonical = typeAliases[this.data.type] ? this.data.type : Object.keys(typeAliases).find((k) => typeAliases[k].includes(this.data.type)) || this.data.type;
        this.data.include_code = codeTypes.includes(canonical);
        this.data.submission_file_format = EXTENSION_MAP[this.data.submission_type] || "";
        this.finish({ ...this.data });
      })
    );
  }
  onClose() {
    this.contentEl.empty();
    if (!this.done)
      this.finish(null);
  }
  finish(data) {
    if (this.done)
      return;
    this.done = true;
    this.close();
    this.resolvePromise(data);
  }
  open() {
    super.open();
    return new Promise((resolve) => this.resolvePromise = resolve);
  }
};
var ObsidianModalPort = class {
  constructor(app) {
    this.app = app;
  }
  async openAssignmentForm(_context, prefill = {}) {
    return new AssignmentFormModal(this.app, prefill).open();
  }
};

// src/adapters/obsidian/vault_adapter.ts
var import_obsidian3 = require("obsidian");
function toVaultFile(file) {
  return {
    path: file.path,
    name: file.name,
    basename: file.basename,
    extension: file.extension,
    parent: null
  };
}
function toVaultFolder(folder) {
  return {
    path: folder.path,
    name: folder.name,
    parent: null,
    children: folder.children.map(
      (child) => child instanceof import_obsidian3.TFile ? toVaultFile(child) : toVaultFolder(child)
    )
  };
}
var ObsidianVaultAdapter = class {
  constructor(app) {
    this.app = app;
  }
  getAbstractFileByPath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!file)
      return null;
    if (file instanceof import_obsidian3.TFile)
      return toVaultFile(file);
    if (file instanceof import_obsidian3.TFolder)
      return toVaultFolder(file);
    return null;
  }
  getVaultBasePath() {
    const adapter = this.app.vault.adapter;
    if (adapter && typeof adapter.getBasePath === "function") {
      return adapter.getBasePath();
    }
    return null;
  }
  async readFile(file) {
    const tFile = this.app.vault.getAbstractFileByPath(file.path);
    if (!(tFile instanceof import_obsidian3.TFile))
      throw new Error(`File not found: ${file.path}`);
    return this.app.vault.read(tFile);
  }
  async createFolder(path) {
    var _a;
    try {
      await this.app.vault.createFolder(path);
    } catch (e) {
      if ((_a = e.message) == null ? void 0 : _a.includes("Folder already exists"))
        return;
      throw e;
    }
  }
  async createFile(path, content) {
    const tFile = await this.app.vault.create(path, content);
    return toVaultFile(tFile);
  }
  async moveFile(file, newPath) {
    const tFile = this.app.vault.getAbstractFileByPath(file.path);
    if (!(tFile instanceof import_obsidian3.TFile))
      throw new Error(`File not found: ${file.path}`);
    await this.app.vault.rename(tFile, newPath);
  }
  getMatchedPath(pattern) {
    var _a, _b;
    return (_b = (_a = this.app.vault.getAbstractFileByPath(pattern)) == null ? void 0 : _a.path) != null ? _b : null;
  }
  getActiveFilePath() {
    var _a, _b;
    return (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : null;
  }
};

// src/adapters/obsidian/settings_adapter.ts
var ObsidianSettingsAdapter = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  getCodeFolderPath() {
    const path = this.plugin.settings.codeFolderPath;
    return path && path.trim() !== "" ? path : void 0;
  }
  getExternalCodeBasePath() {
    const path = this.plugin.settings.externalCodeBasePath;
    return path && path.trim() !== "" ? path : void 0;
  }
};

// src/ports/file_system_port.ts
var FileSystemError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "FileSystemError";
  }
};

// src/adapters/obsidian/file_system_adapter.ts
var fs = __toESM(require("fs"));
var import_path = require("path");
var ObsidianFileSystemAdapter = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.isDesktopAvailable = typeof process !== "undefined" && !!fs.promises;
  }
  isDesktop() {
    return this.isDesktopAvailable;
  }
  getVaultBasePath() {
    const adapter = this.plugin.app.vault.adapter;
    if (adapter && typeof adapter.getBasePath === "function") {
      return adapter.getBasePath();
    }
    return null;
  }
  async createDir(path) {
    try {
      await fs.promises.mkdir(path, { recursive: true });
    } catch (e) {
      if (e.code === "EEXIST")
        return;
      throw new FileSystemError(`Failed to create dir '${path}': ${e.message}`);
    }
  }
  async exists(path) {
    try {
      await fs.promises.access(path);
      return true;
    } catch (e) {
      return false;
    }
  }
  async symlink(target, linkPath) {
    try {
      const linkDir = (0, import_path.dirname)(linkPath);
      await this.createDir(linkDir);
      const alreadyExists = await this.exists(linkPath);
      if (alreadyExists) {
        try {
          await fs.promises.unlink(linkPath);
        } catch (e) {
          throw new FileSystemError(`Symlink '${linkPath}' exists and cannot be removed: ${e.message}`);
        }
      }
      const targetIsDir = (await fs.promises.stat(target)).isDirectory();
      await fs.promises.symlink(target, linkPath, targetIsDir ? "junction" : "file");
    } catch (e) {
      if (e instanceof FileSystemError)
        throw e;
      throw new FileSystemError(`Failed to symlink '${target}' -> '${linkPath}': ${e.message}`);
    }
  }
};

// src/use_cases/assignment_number_service.ts
var AssignmentNumberService = class {
  constructor(vaultPort) {
    this.vaultPort = vaultPort;
  }
  async scanLastOfType(type, context) {
    var _a;
    const dirPath = `${context.coursePath}/${context.assignDir}`;
    const folder = this.vaultPort.getAbstractFileByPath(dirPath);
    if (!folder || !folder.children)
      return null;
    const aliases = typeAliases[type] || [type];
    const candidates = folder.children.filter((child) => "children" in child && child.children !== void 0).filter((child) => {
      const m = child.name.match(/^\d{4}-\d{2}-\d{2}-(.+)$/);
      if (!m)
        return false;
      return aliases.some((a) => m[1] === a || m[1].startsWith(`${a}-`));
    }).sort((a, b) => b.name.localeCompare(a.name));
    if (candidates.length === 0)
      return null;
    for (const candidate of candidates) {
      const note = (_a = candidate.children) == null ? void 0 : _a.find(
        (c) => "extension" in c && c.extension === "md" && !c.name.startsWith("_")
      );
      if (!note)
        continue;
      const content = await this.vaultPort.readFile(note);
      const fm = this.parseFrontmatter(content);
      if (fm)
        return fm;
    }
    return null;
  }
  async scanLastOverall(context) {
    var _a;
    const dirPath = `${context.coursePath}/${context.assignDir}`;
    const folder = this.vaultPort.getAbstractFileByPath(dirPath);
    if (!folder || !folder.children)
      return null;
    const candidates = folder.children.filter((child) => "children" in child && child.children !== void 0).filter((child) => /^\d{4}-\d{2}-\d{2}-/.test(child.name)).sort((a, b) => b.name.localeCompare(a.name));
    if (candidates.length === 0)
      return null;
    for (const candidate of candidates) {
      const note = (_a = candidate.children) == null ? void 0 : _a.find(
        (c) => "extension" in c && c.extension === "md" && !c.name.startsWith("_")
      );
      if (!note)
        continue;
      const content = await this.vaultPort.readFile(note);
      const fm = this.parseFrontmatter(content);
      if (fm)
        return fm;
    }
    return null;
  }
  async getNextAssignmentNumber(type, context) {
    const lastOfType = await this.scanLastOfType(type, context);
    if (lastOfType && lastOfType.assignment_number) {
      return String(parseInt(lastOfType.assignment_number, 10) + 1).padStart(2, "0");
    }
    return "01";
  }
  async getNextUnit(context) {
    const lastOverall = await this.scanLastOverall(context);
    if (lastOverall && lastOverall.unit) {
      return String(parseInt(lastOverall.unit, 10)).padStart(2, "0");
    }
    return "01";
  }
  parseFrontmatter(content) {
    const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
    if (!fmMatch)
      return null;
    const fm = fmMatch[1];
    const get = (key) => {
      const m = fm.match(new RegExp(`^${key}:\\s*"?([^"\\n]+)"?`, "m"));
      return m ? m[1].trim() : null;
    };
    const unit = get("unit");
    const assignment_number = get("assignment_number");
    if (!unit && !assignment_number)
      return null;
    return {
      unit: unit != null ? unit : void 0,
      assignment_number: assignment_number != null ? assignment_number : void 0
    };
  }
};

// src/domain/slugify.ts
var slugify = (text) => {
  return text.normalize("NFKD").toLowerCase().replace(/[^\w\s-]/g, "").trim().replace(/[\s-]+/g, "-");
};

// src/domain/assignment_domain.ts
var codeTypes2 = codeTypes;
var resolveType2 = resolveType;
function pad2(value, fallback = "01") {
  return String(value != null ? value : fallback).padStart(2, "0");
}
function buildTitle(params) {
  const unitPadded = pad2(params.unit);
  const numPadded = pad2(params.assignmentNumber);
  const topicStr = params.topic || "Introduccion";
  const display = getDisplayName(params.type || "practico");
  if (params.courseName) {
    return `${params.courseName} - Unidad ${unitPadded} - ${display} ${numPadded} - ${topicStr}`;
  }
  return `Unidad ${unitPadded} - ${display} ${numPadded} - ${topicStr}`;
}
function buildFilename(params) {
  const dateStr = params.date;
  const studentSlug = slugify(params.student || "");
  const rawCourse = params.courseCode && params.courseCode !== "" && params.courseCode !== "undefined" ? params.courseCode : params.courseName || "curso";
  const courseSlug = slugify(rawCourse);
  const typeSlug = slugify(params.type || "practico");
  const numPadded = pad2(params.assignmentNumber);
  const topicSlug = slugify(params.topic || "Introduccion");
  return `${dateStr}-${studentSlug}-${courseSlug}-${typeSlug}-${numPadded}-${topicSlug}`;
}
function buildFolderName(params) {
  const typeSlug = slugify(params.type || "practico");
  const topicSlug = slugify(params.topic || "Introduccion");
  return `${params.date}-${typeSlug}-${topicSlug}`;
}
function buildBasePath(params) {
  return `${params.coursePath}/${params.assignDir}/${params.folderName}`;
}
function getScaffoldDirs(typeSlug, includeCode = null) {
  const canonical = resolveType2(typeSlug);
  const base = scaffoldTemplates[canonical] || scaffoldTemplates[typeSlug] || ["_assets", "deliverable"];
  const dirs = [...base];
  const shouldInclude = includeCode !== null ? includeCode : codeTypes2.includes(canonical);
  if (shouldInclude && !dirs.includes("code"))
    dirs.push("code");
  return dirs;
}
function normalizeUnit(unit) {
  return pad2(unit, "01");
}
function normalizeNumber(n) {
  return pad2(n, "01");
}
function buildExternalCodePath(params) {
  const subjectSlug = slugify(params.subject);
  return `${params.externalBase}/${subjectSlug}/${params.folderName}`;
}

// src/use_cases/create_assignment_service.ts
var CreateAssignmentService = class {
  constructor(vaultPort, settingsPort, fsPort) {
    this.vaultPort = vaultPort;
    this.settingsPort = settingsPort;
    this.fsPort = fsPort;
  }
  async execute(formData, context) {
    var _a, _b;
    const typeSlug = formData.type;
    const unit = normalizeUnit(formData.unit);
    const assignmentNumber = normalizeNumber(formData.assignment_number);
    const topic = formData.topic || "Introduccion";
    const title = buildTitle({
      courseName: context.course.name,
      unit,
      type: typeSlug,
      assignmentNumber,
      topic
    });
    const filenameBase = buildFilename({
      date: context.date,
      student: context.career.student,
      courseCode: context.course.code,
      courseName: context.course.name,
      type: typeSlug,
      assignmentNumber,
      topic
    });
    const filename = `${filenameBase}.md`;
    const folderName = buildFolderName({ date: context.date, type: typeSlug, topic });
    const basePath = buildBasePath({ coursePath: context.coursePath, assignDir: context.assignDir, folderName });
    const includeCode = formData.include_code === true;
    const canonicalType = typeSlug;
    const shouldCreateCode = includeCode || codeTypes2.includes(canonicalType);
    const dirs = getScaffoldDirs(typeSlug, includeCode);
    const externalCodeBase = this.settingsPort.getExternalCodeBasePath();
    const vaultCodePath = this.settingsPort.getCodeFolderPath();
    const subject = context.coursePath.split("/").pop() || "";
    const shouldUseVaultCodePath = !!vaultCodePath && !externalCodeBase;
    for (const dir of dirs) {
      if (dir === "code" && (externalCodeBase || shouldUseVaultCodePath))
        continue;
      await this.vaultPort.createFolder(`${basePath}/${dir}`);
    }
    if (shouldCreateCode) {
      if (externalCodeBase) {
        if (this.fsPort.isDesktop()) {
          const externalPath = buildExternalCodePath({
            externalBase: externalCodeBase,
            subject,
            folderName
          });
          await this.fsPort.createDir(externalPath);
          const vaultBase = ((_b = (_a = this.vaultPort).getVaultBasePath) == null ? void 0 : _b.call(_a)) || "";
          const codeLinkPath = `${vaultBase}/${basePath}/code`;
          await this.fsPort.symlink(externalPath, codeLinkPath);
        } else {
          console.warn("External code base set but not on desktop, falling back to vault folder");
          await this.vaultPort.createFolder(`${basePath}/code`);
        }
      } else if (vaultCodePath) {
        await this.vaultPort.createFolder(`${vaultCodePath}/${folderName}-code`);
      }
    }
    const frontmatter = this.buildFrontmatter({
      title,
      filename,
      type: typeSlug,
      date: context.date,
      due_date: formData.due_date,
      author: context.career.student,
      course: context.course,
      unit,
      assignmentNumber,
      topic,
      difficulty: formData.difficulty,
      priority: formData.priority,
      submission_type: formData.submission_type,
      submission_file_format: formData.submission_file_format || "",
      submission_platform: formData.submission_platform,
      instructions_link: formData.instructions_link,
      submission_link: formData.submission_link,
      ai_chat_links: formData.ai_chat_links
    });
    const body = this.buildBody({
      title,
      student: context.career.student,
      submission_link: formData.submission_link,
      instructions_link: formData.instructions_link,
      submission_file_format: formData.submission_file_format || ""
    });
    const path = `${basePath}/${filename}`;
    await this.vaultPort.createFile(path, frontmatter + "\n" + body);
    return { title, filename, basePath, frontmatter, body, path };
  }
  buildBody(params) {
    return `# ${params.title}
<!--
- **Materia**: \`= this.course.name\`
- **Unidad**: \`= this.unit\`
- **Actividad**: \`= this.assignment\`
- **Tema**: \`= this.topic\`
- **Profesor**: \`= this.professor\`
- **Estudiante**: \`= this.student\`
- **Fecha de entrega**: \`= this.due_date\`
- **Completado**: \`= this.status_completed\`
- **Instrucciones**: \`= this.links_instructions\`
- **Copia Local**: \`= this.links_local_file\`
- **Enlace de Entrega**: \`= this.links_submission\`
- **Estudiante**: ${params.student}
-->

## \u{1F4CC} Descripci\xF3n de la Actividad

- [Plataforma de Entrega](${params.submission_link}) | [Instrucciones](${params.instructions_link})
- Objetivos principales:
	- Desarrollar consignas te\xF3rica-pr\xE1cticas
- Formato de entrega requerido: **${params.submission_file_format}**

## \u{1F4DD} Desarrollo

### Punto 1



## \u{1F6E0}\uFE0F Desarrollo Pr\xE1ctico



## \u{1F4DA} Material de Referencia

- ...

## \u{1F4C2} Archivos Adjuntos

- ...`;
  }
  buildFrontmatter(params) {
    const topicSlug = params.topic.normalize("NFKD").toLowerCase().replace(/[^\w\s-]/g, "").trim().replace(/[\s-]+/g, "-");
    const typeSlug = params.type.normalize("NFKD").toLowerCase().replace(/[^\w\s-]/g, "").trim().replace(/[\s-]+/g, "-");
    const aiChatLinks = params.ai_chat_links.split("\n").filter((link) => link.trim()).map((item) => `  - ${item.trim()}`).join("\n");
    return `---
title: "${params.title}"
filename: "${params.filename}"
type: "${params.type}"
date: "${params.date}"
due_date: "${params.due_date}"
author: "${params.author}"
course:
  name: "${params.course.name}"
  code: "${params.course.code}"
unit: "${params.unit}"
assignment_number: "${params.assignmentNumber}"
topic: "${params.topic}"
difficulty: ${params.difficulty}
priority: ${params.priority}
status_completed: false
status_submitted: false
status_graded: false
grading:
  max_points: 100
  earned_points: 0
  weight: 0.00
submission_type: "${params.submission_type}"
submission_file_format: "${params.submission_file_format}"
submission_platform: "${params.submission_platform}"
links_instructions: "${params.instructions_link}"
links_submission: "${params.submission_link}"
links_local_copy: ""
ai_chat_links:
${aiChatLinks ? "\n" + aiChatLinks : ""}
tags:
- ${topicSlug}
- second-year
- ${typeSlug}
- unit-${params.unit}
toc: false
---`;
  }
};

// src/plugin/main.ts
var AcademicCMSPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new AcademicCMSSettingTab(this.app, this));
    this.vaultAdapter = new ObsidianVaultAdapter(this.app);
    this.settingsAdapter = new ObsidianSettingsAdapter(this);
    this.fsAdapter = new ObsidianFileSystemAdapter(this);
    this.addCommand({
      id: "create-assignment",
      name: "Create Assignment",
      checkCallback: (checking) => {
        const ctx = this.getContextFromActiveFile();
        if (checking)
          return !!ctx;
        if (!ctx)
          return false;
        this.openAssignmentModalForContext(ctx).catch(console.error);
        return true;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian4.TFolder) {
          const ctx = this.getContextFromPath(file.path);
          if (ctx) {
            menu.addItem(
              (item) => item.setTitle("New Assignment").setIcon("folder-plus").onClick(() => this.openAssignmentModalForPath(file.path))
            );
          }
        }
      })
    );
    console.log("Academic CMS loaded");
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  matchPathPattern(activePath, pathPattern) {
    const normalized = pathPattern.replace(/^\/|\/$/g, "");
    const regexParts = normalized.split("/").filter(Boolean).map((segment) => segment === "*" ? "[^/]+" : segment.replace(/\*/g, "[^/]*"));
    const pathRegex = new RegExp(`^${regexParts.join("\\/")}(\\/|$)`, "i");
    if (!pathRegex.test(activePath))
      return null;
    const segments = activePath.split("/").filter(Boolean);
    return segments.slice(0, regexParts.length).join("/") || null;
  }
  findSubjectPathFromPath(filePath) {
    const parts = filePath.split("/");
    const subjectsIdx = parts.findIndex((p) => p === "subjects");
    if (subjectsIdx === -1)
      return null;
    if (subjectsIdx + 2 > parts.length)
      return null;
    return parts.slice(0, subjectsIdx + 2).join("/");
  }
  getContextFromPath(filePath) {
    var _a, _b, _c, _d;
    const coursePath = this.matchPathPattern(filePath, "*/*systems*/subjects/*/") || this.findSubjectPathFromPath(filePath);
    if (!coursePath)
      return null;
    const assignDir = filePath.includes("/40-exams/") ? "40-exams" : "30-assignments";
    let course;
    const courseFile = this.app.vault.getAbstractFileByPath(`${coursePath}/_course.md`);
    if (courseFile instanceof import_obsidian4.TFile) {
      const fm = (_a = this.app.metadataCache.getFileCache(courseFile)) == null ? void 0 : _a.frontmatter;
      if (fm == null ? void 0 : fm.course)
        course = { name: fm.course, code: (_b = fm.code) != null ? _b : "" };
    }
    let career;
    const careerPath = coursePath.split("/").slice(0, -2).join("/");
    const careerFile = this.app.vault.getAbstractFileByPath(`${careerPath}/_career.md`);
    if (careerFile instanceof import_obsidian4.TFile) {
      const student = (_d = (_c = this.app.metadataCache.getFileCache(careerFile)) == null ? void 0 : _c.frontmatter) == null ? void 0 : _d.student;
      if (student)
        career = { student };
    }
    return { coursePath, assignDir, course, career };
  }
  getContextFromActiveFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!(activeFile == null ? void 0 : activeFile.path)) {
      new import_obsidian4.Notice("Academic CMS: no active file");
      return null;
    }
    const context = this.getContextFromPath(activeFile.path);
    if (!context) {
      new import_obsidian4.Notice("No se detect\xF3 una materia \u2014 run this from inside a course folder");
    }
    return context;
  }
  async openAssignmentModal() {
    const context = this.getContextFromActiveFile();
    if (!context)
      return;
    await this.openAssignmentModalForContext(context);
  }
  async openAssignmentModalForPath(path) {
    const context = this.getContextFromPath(path);
    if (!context)
      return;
    await this.openAssignmentModalForContext(context);
  }
  async openAssignmentModalForContext(context) {
    try {
      if (!context.course || !context.career) {
        new import_obsidian4.Notice("Academic CMS: missing course or career metadata (_course.md / _career.md)");
        return;
      }
      const numberService = new AssignmentNumberService(this.vaultAdapter);
      const today = /* @__PURE__ */ new Date();
      const iso = (d) => d.toISOString().slice(0, 10);
      const addDays = (d, days) => new Date(d.getTime() + days * 864e5);
      const prefill = {
        unit: await numberService.getNextUnit(context),
        date: iso(today),
        due_date: iso(addDays(today, 7))
      };
      const modal = new ObsidianModalPort(this.app);
      const data = await modal.openAssignmentForm(context, prefill);
      if (!data) {
        new import_obsidian4.Notice("Creaci\xF3n cancelada");
        return;
      }
      data.assignment_number = await numberService.getNextAssignmentNumber(
        data.type,
        context
      );
      const createService = new CreateAssignmentService(
        this.vaultAdapter,
        this.settingsAdapter,
        this.fsAdapter
      );
      const result = await createService.execute(data, {
        coursePath: context.coursePath,
        assignDir: context.assignDir,
        course: context.course,
        career: context.career,
        date: data.date || prefill.date || ""
      });
      new import_obsidian4.Notice(`Created: ${result.title}`);
      const created = this.app.vault.getAbstractFileByPath(result.path);
      if (created instanceof import_obsidian4.TFile || created instanceof import_obsidian4.TFolder) {
        await this.app.workspace.getLeaf().openFile(this.app.vault.getAbstractFileByPath(result.path));
      }
    } catch (e) {
      console.error("Academic CMS: failed to create assignment", e);
      new import_obsidian4.Notice(`Academic CMS error: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
};
