/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/plugin/settings.ts
var settings_exports = {};
__export(settings_exports, {
  AcademicCMSSettingTab: () => AcademicCMSSettingTab,
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS
});
var import_obsidian, DEFAULT_SETTINGS, AcademicCMSSettingTab;
var init_settings = __esm({
  "src/plugin/settings.ts"() {
    import_obsidian = require("obsidian");
    DEFAULT_SETTINGS = {
      codeFolderPath: ""
    };
    AcademicCMSSettingTab = class extends import_obsidian.PluginSettingTab {
      constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
      }
      display() {
        const { containerEl } = this;
        containerEl.empty();
        containerEl.createEl("h2", { text: "Academic CMS Settings" });
        new import_obsidian.Setting(containerEl).setName("Code folder path").setDesc("Vault-relative path for code/ when assignment type includes code (e.g. practico). Leave empty for default vault folder structure: course/assignDir/folder/code. Agnostic, no hardcode ~/Projects.").addText(
          (text) => text.setPlaceholder("e.g. 30-assignments or leave empty").setValue(this.plugin.settings.codeFolderPath).onChange(async (value) => {
            this.plugin.settings.codeFolderPath = value;
            await this.plugin.saveSettings();
          })
        );
      }
    };
  }
});

// src/plugin/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AcademicCMSPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");
init_settings();
var AcademicCMSPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new (await Promise.resolve().then(() => (init_settings(), settings_exports))).AcademicCMSSettingTab(this.app, this));
    this.addCommand({
      id: "create-assignment",
      name: "Create Assignment",
      callback: () => this.openAssignmentModal()
    });
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (!(file instanceof import_obsidian2.TFile))
          return;
      })
    );
    console.log("Academic CMS loaded");
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async openAssignmentModal() {
    new import_obsidian2.Notice("Academic CMS: Create Assignment \u2014 TODO: open ModalPort (Phase 3b)");
  }
};
